plugins:
  skillways_discourse_bridge_api_key:
    default: '<place-api-key-here>'
    client: true
  skillways_discourse_bridge_api_user:
    default: 'system'
    client: true
  skillways_discourse_bridge_enabled:
    default: true
    client: true
  skillways_discourse_bridge_jwt_secret:
    default: '<place-jwt-secret-here>'
